const fs   = require("fs");
const path = require("path");

// ── Firebase placeholder replacements ────────────────────────────
const replacements = {
  __FIREBASE_API_KEY__:             process.env.FIREBASE_API_KEY             || "",
  __FIREBASE_AUTH_DOMAIN__:         process.env.FIREBASE_AUTH_DOMAIN         || "",
  __FIREBASE_PROJECT_ID__:          process.env.FIREBASE_PROJECT_ID          || "",
  __FIREBASE_STORAGE_BUCKET__:      process.env.FIREBASE_STORAGE_BUCKET      || "",
  __FIREBASE_MESSAGING_SENDER_ID__: process.env.FIREBASE_MESSAGING_SENDER_ID || "",
  __FIREBASE_APP_ID__:              process.env.FIREBASE_APP_ID              || "",
};

// ── Clean URL mapping ─────────────────────────────────────────────
const cleanUrls = {
  "index.html":        "",
  "olympiad.html":     "olympiad",
  "universities.html": "universities",
  "placement.html":    "placement",
  "scholarships.html": "scholarships",
  "teachers.html":     "teachers",
};

function rewriteLinks(content) {
  let result = content;
  for (const [filename, slug] of Object.entries(cleanUrls)) {
    const escaped = filename.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const target  = slug === "" ? "/" : `/${slug}`;
    result = result.replace(
      new RegExp(`(href=")(\\./)?(${escaped})(")`, "g"),
      `$1${target}$4`
    );
    result = result.replace(
      new RegExp(`(window\\.location(?:\\.href|\\.replace)\\s*[=(]\\s*")(\\./)?(${escaped})(")`, "g"),
      `$1${target}$4`
    );
  }
  return result;
}

// ── Create dist ───────────────────────────────────────────────────
if (!fs.existsSync("dist")) fs.mkdirSync("dist");

// ── Process HTML files ────────────────────────────────────────────
for (const [file, slug] of Object.entries(cleanUrls)) {
  if (!fs.existsSync(file)) { console.warn(`Skipping missing: ${file}`); continue; }
  let html = fs.readFileSync(file, "utf8");

  // Replace Firebase placeholders
  for (const [placeholder, value] of Object.entries(replacements)) {
    html = html.replace(new RegExp(placeholder, "g"), value);
  }

  // Strip local-dev firebase-config.js tag
  html = html.replace(/<script src="firebase-config\.js"><\/script>\n?/g, "");

  // Rewrite internal links
  html = rewriteLinks(html);

  const destName = slug === "" ? "index.html" : `${slug}.html`;
  fs.writeFileSync(path.join("dist", destName), html);
  console.log(`Processed: ${file} → dist/${destName}`);
}

// ── resources/ folder ─────────────────────────────────────────────
const resDir = path.join("dist", "resources");
if (!fs.existsSync(resDir)) fs.mkdirSync(resDir);
const resFiles = ["scholarship-data.json", "Teachers Database.xlsx"];
for (const f of resFiles) {
  const src = path.join("resources", f);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(resDir, f));
    console.log(`Copied: resources/${f}`);
  }
}

// ── auth-guard.js ─────────────────────────────────────────────────
if (fs.existsSync("auth-guard.js")) {
  let js = fs.readFileSync("auth-guard.js", "utf8");
  js = rewriteLinks(js);
  fs.writeFileSync("dist/auth-guard.js", js);
  console.log("Processed: auth-guard.js");
}

// ── Generate _redirects ───────────────────────────────────────────
let redirects = "# Clean URL routing (generated by build.js)\n\n";
for (const [filename, slug] of Object.entries(cleanUrls)) {
  if (slug === "") continue;
  redirects += `/${slug}  /${slug}.html  200\n`;
  if (filename !== `${slug}.html`) {
    redirects += `/${filename}  /${slug}  301\n`;
  }
}
fs.writeFileSync(path.join("dist", "_redirects"), redirects);
console.log("Generated: _redirects");

// ── Summary ───────────────────────────────────────────────────────
console.log("\nBuild completed!");
Object.keys(replacements).forEach(key => {
  console.log(`  ${key}: ${replacements[key] ? "[SET]" : "[NOT SET]"}`);
});
